"""Turn results/sf*/ into results/SUMMARY.md tables and results/charts/*.png.

    python analysis/report.py

A cell counts only when every run in it succeeded and its result hash matched
path A ("ref"/"yes"). Latency = median of the warm runs. Tier aggregates are
geometric means over the queries that are valid for every path compared.
"""
import csv
import json
import math
import pathlib
import statistics
from collections import defaultdict

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

LAB = pathlib.Path(__file__).resolve().parents[1]
RES = LAB / "results"
CHARTS = RES / "charts"
PATHS = ["A", "B", "B2", "C"]
LABEL = {"A": "A pg_lake", "B": "B pg_duckdb 1.1.1", "B2": "B' pg_duckdb main", "C": "C pg_clickhouse"}
# reference palette slots 1-4, assigned by entity (never by rank)
COLOR = {"A": "#2a78d6", "B": "#eb6834", "B2": "#eda100", "C": "#1baf7a"}
TIERS = ["L1", "L2", "L3", "L4", "L5"]
INK, MUTED, GRID = "#0b0b0b", "#52514e", "#e4e3df"


def rows(path):
    if not path.exists():
        return []
    with open(path) as f:
        return list(csv.DictReader(f))


def geomean(xs):
    xs = [x for x in xs if x and x > 0]
    return math.exp(sum(map(math.log, xs)) / len(xs)) if xs else None


def fmt_ms(v):
    if v is None:
        return "–"
    if isinstance(v, str):
        return v
    return f"{v / 1000:.2f} s" if v >= 1000 else f"{v:.0f} ms"


# ------------------------------------------------------------------ cells
def cells(sf, mode="per-node"):
    """(path, dim, qid) -> dict(status, warm_p50, cold, pg_cpu, engine_cpu, s3_cold, tier, pushdown)."""
    data = [r for r in rows(RES / f"sf{sf}" / "bench.csv") if r["resource_mode"] == mode]
    out = {}
    grouped = defaultdict(list)
    for r in data:
        grouped[(r["path"], r["dim_scenario"], r["query_id"])].append(r)
    for k, rs in grouped.items():
        last_run = rs[-1]["run_id"]  # a re-run of a cell supersedes the earlier one
        rs = [r for r in rs if r["run_id"] == last_run]
        runs = [r for r in rs if r["run_type"] in ("cold", "warm", "warmup")]
        exp = next((r["pushdown"] for r in rs if r["run_type"] == "explain"), "")
        bad = next((r for r in runs if r["status"] != "ok"), None)
        wrong = any(r["hash_match"] == "NO" for r in runs)
        warm = [float(r["latency_ms"]) for r in runs if r["run_type"] == "warm" and r["status"] == "ok"]
        cold = next((float(r["latency_ms"]) for r in runs if r["run_type"] == "cold" and r["status"] == "ok"), None)
        c0 = next((r for r in runs if r["run_type"] == "cold"), {})

        def med(field):
            v = [float(r[field]) for r in runs if r["run_type"] == "warm" and r.get(field) not in ("", None)]
            return statistics.median(v) if v else None
        status = "wrong" if wrong else (bad["status"] if bad else "ok")
        out[k] = {"status": status, "tier": runs[0]["tier"] if runs else "",
                  "warm_p50": statistics.median(warm) if warm and status == "ok" else None,
                  "cold": cold if status == "ok" else None,
                  "pg_cpu": med("pg_main_cpu_s"), "engine_cpu": med("engine_cpu_s"),
                  "engine_mem": med("engine_peak_mem_mb"),
                  "s3_cold_mb": (int(c0["s3_bytes_read"]) / 2**20) if c0.get("s3_bytes_read") else None,
                  "pushdown": exp, "error": bad["error"] if bad else ""}
    return out


def cell_text(c):
    if c is None:
        return "·"
    if c["status"] == "ok":
        return fmt_ms(c["warm_p50"])
    return {"DNF": "DNF", "wrong": "**wrong**", "crash": "crash", "error": "error"}[c["status"]]


def sfs():
    return sorted(int(p.name[2:]) for p in RES.glob("sf*") if (p / "bench.csv").exists())


# ------------------------------------------------------------------ report
def main():
    CHARTS.mkdir(parents=True, exist_ok=True)
    md = ["# Summary tables (generated by analysis/report.py)", ""]
    tier_gm = {}  # (sf, tier, path) -> geomean over the common valid set
    for sf in sfs():
        cs = cells(sf)
        present = [p for p in PATHS if any(k[0] == p for k in cs)]
        md += [f"## SF{sf} — warm p50 per query", "",
               "| Tier | Query | Dim | " + " | ".join(LABEL[p] for p in present) + " | pushdown A/B/B'/C |",
               "|---|---|---|" + "---|" * len(present) + "---|"]
        keys = sorted({(k[1], k[2]) for k in cs}, key=lambda x: (cs.get(("A", x[0], x[1]), {}).get("tier", ""), x[1], x[0]))
        for dim, q in keys:
            tier = next((cs[(p, dim, q)]["tier"] for p in present if (p, dim, q) in cs), "")
            pd = "/".join((cs.get((p, dim, q)) or {}).get("pushdown", "") or "·" for p in present)
            md.append(f"| {tier} | {q} | {dim} | " + " | ".join(cell_text(cs.get((p, dim, q))) for p in present) + f" | {pd} |")
        md.append("")
        # tier geomeans over queries valid for all present paths (D1 only; D2 separately)
        for dim in ("D1", "D2"):
            dq = {k[2] for k in cs if k[1] == dim}
            if not dq:
                continue
            # a path that ran only a few queries (B in the light run) is not compared
            full = [p for p in present if all((p, dim, q) in cs for q in dq)]
            md += [f"### SF{sf} {dim} — tier geomean of warm p50 (queries valid on every path)", "",
                   "| Tier | n | " + " | ".join(LABEL[p] for p in full) + " | fastest |", "|---|---|" + "---|" * len(full) + "---|"]
            for t in TIERS:
                qs = sorted({k[2] for k in cs if k[1] == dim and cs[k]["tier"] == t})
                ok = [q for q in qs if all((cs.get((p, dim, q)) or {}).get("status") == "ok" for p in full)]
                if not qs:
                    continue
                gms = {p: geomean([cs[(p, dim, q)]["warm_p50"] for q in ok]) for p in full}
                for p, g in gms.items():
                    tier_gm[(sf, dim, t, p)] = g
                best = min((p for p in full if gms[p]), key=lambda p: gms[p], default=None)
                excluded = sorted(set(qs) - set(ok))
                md.append(f"| {t} | {len(ok)}/{len(qs)} | " + " | ".join(fmt_ms(gms[p]) for p in full)
                          + f" | {LABEL[best] if best else '–'}{' (excl. ' + ', '.join(excluded) + ')' if excluded else ''} |")
            md.append("")
        # main-node load
        md += [f"### SF{sf} — main Postgres node CPU per warm query (median core-seconds)", "",
               "| Query | Dim | A pg-main (of which pgduck_server) | C pg-main | C ClickHouse | B / B' separate node |", "|---|---|---|---|---|---|"]
        for dim, q in keys:
            a, c, b, b2 = (cs.get((p, dim, q)) for p in ("A", "C", "B", "B2"))
            duck = [float(r["pg_main_pgduck_cpu_s"]) for r in rows(RES / f"sf{sf}" / "bench.csv")
                    if r["path"] == "A" and r["dim_scenario"] == dim and r["query_id"] == q
                    and r["run_type"] == "warm" and r["pg_main_pgduck_cpu_s"] not in ("",)]
            f = lambda x: f"{x:.2f}" if x is not None else "–"  # noqa: E731
            md.append(f"| {q} | {dim} | {f(a and a['pg_cpu'])} ({f(statistics.median(duck) if duck else None)}) | "
                      f"{f(c and c['pg_cpu'])} | {f(c and c['engine_cpu'])} | {f(b and b['engine_cpu'])} / {f(b2 and b2['engine_cpu'])} |")
        md.append("")
        # equal-total mode for C
        et = cells(sf, "equal-total")
        if et:
            md += [f"### SF{sf} — path C, per-node (4+4 CPU) vs equal-total (2+2 CPU), warm p50", "",
                   "| Query | Dim | C per-node | C equal-total | A (4 CPU) |", "|---|---|---|---|---|"]
            for dim, q in keys:
                md.append(f"| {q} | {dim} | {cell_text(cs.get(('C', dim, q)))} | {cell_text(et.get(('C', dim, q)))} | {cell_text(cs.get(('A', dim, q)))} |")
            md.append("")
        # C with ClickHouse's join build side swapped (pg_clickhouse.session_settings)
        js = cells(sf, "join-swap")
        if js:
            md += [f"### SF{sf} — path C default vs `query_plan_join_swap_table 1`, warm p50", "",
                   "| Query | Dim | C default | C join-swap | B' pg_duckdb main |", "|---|---|---|---|---|"]
            for dim, q in keys:
                md.append(f"| {q} | {dim} | {cell_text(cs.get(('C', dim, q)))} | {cell_text(js.get(('C', dim, q)))} | {cell_text(cs.get(('B2', dim, q)))} |")
            md.append("")
        # errors
        errs = [(k, v) for k, v in cs.items() if v["status"] not in ("ok",)]
        if errs:
            md += [f"### SF{sf} — failed or invalid cells", "", "| Path | Dim | Query | Status | Detail |", "|---|---|---|---|---|"]
            for (p, dim, q), v in sorted(errs):
                md.append(f"| {LABEL[p]} | {dim} | {q} | {v['status']} | {v['error'][:120]} |")
            md.append("")
        for name in ("tiering", "layout", "concurrency", "direct", "faults", "ilm_deletes", "ilm_freshness", "ilm_expiry"):
            rs = rows(RES / f"sf{sf}" / f"{name}.csv")
            if not rs:
                continue
            if name == "tiering":
                by = defaultdict(list)
                for r in rs:
                    by[r["table"]].append(r)
                md += [f"### SF{sf} — tiering (monthly heap → Iceberg commits)", "",
                       "| Table | Months | Rows | Total s | Median s / month | Rows/s |", "|---|---|---|---|---|---|"]
                for t, v in by.items():
                    n = sum(int(r["rows"]) for r in v)
                    s = sum(float(r["seconds"]) for r in v)
                    md.append(f"| {t} | {len(v)} | {n:,} | {s:.0f} | {statistics.median(float(r['seconds']) for r in v):.2f} | {n / s:,.0f} |")
                md.append("")
                continue
            md += [f"### SF{sf} — {name}", "", "| " + " | ".join(rs[0]) + " |", "|" + "---|" * len(rs[0])]
            md += ["| " + " | ".join(str(r[c]) for c in rs[0]) + " |" for r in rs]
            md.append("")
    (RES / "SUMMARY.md").write_text("\n".join(md) + "\n")
    charts(tier_gm)
    print("wrote results/SUMMARY.md and results/charts/")


# ------------------------------------------------------------------ charts
def style(ax):
    ax.spines[["top", "right"]].set_visible(False)
    ax.spines[["left", "bottom"]].set_color(MUTED)
    ax.tick_params(colors=MUTED, labelsize=9)
    ax.yaxis.grid(True, color=GRID, linewidth=0.8)
    ax.set_axisbelow(True)


def charts(tier_gm):
    for dim in ("D1",):
        all_sf = sorted({k[0] for k in tier_gm})
        if not all_sf:
            return
        fig, axes = plt.subplots(1, len(all_sf), figsize=(6.2 * len(all_sf), 3.9), squeeze=False)
        for ax, sf in zip(axes[0], all_sf):
            paths = [p for p in PATHS if any(k[0] == sf and k[3] == p and tier_gm[k] for k in tier_gm)]
            w = 0.8 / max(1, len(paths))
            for i, p in enumerate(paths):
                ys = [tier_gm.get((sf, dim, t, p)) for t in TIERS]
                xs = [j + (i - (len(paths) - 1) / 2) * w for j in range(len(TIERS))]
                ax.bar([x for x, y in zip(xs, ys) if y], [y / 1000 for y in ys if y], width=w - 0.03,
                       color=COLOR[p], label=LABEL[p], edgecolor="white", linewidth=1)
            ax.set_yscale("log")
            ax.set_xticks(range(len(TIERS)), TIERS)
            ax.set_title(f"SF{sf} · all-lake dimensions (D1)", color=INK, fontsize=11, loc="left")
            ax.set_ylabel("warm p50, geomean (s, log)", color=MUTED, fontsize=9)
            style(ax)
        axes[0][0].legend(frameon=False, fontsize=8, loc="upper left")
        fig.tight_layout()
        fig.savefig(CHARTS / "tier_latency.png", dpi=150)
        plt.close(fig)
    # concurrency
    for sf in sfs():
        rs = rows(RES / f"sf{sf}" / "concurrency.csv")
        if not rs:
            continue
        qids = sorted({r["query_id"] for r in rs})
        fig, axes = plt.subplots(2, len(qids), figsize=(5.2 * len(qids), 6.4), squeeze=False)
        for j, q in enumerate(qids):
            for p in PATHS:
                v = sorted(((int(r["clients"]), r) for r in rs if r["path"] == p and r["query_id"] == q), key=lambda x: x[0])
                if not v:
                    continue
                xs = [c for c, _ in v]
                axes[0][j].plot(xs, [float(r["qps"]) for _, r in v], marker="o", markersize=5, linewidth=2,
                                color=COLOR[p], label=LABEL[p])
                busy = [(c, float(r["pg_main_busy_cores"])) for c, r in v if r["pg_main_busy_cores"] not in ("",)]
                if busy:
                    axes[1][j].plot([c for c, _ in busy], [b for _, b in busy], marker="o", markersize=5,
                                    linewidth=2, color=COLOR[p], label=LABEL[p])
            axes[0][j].set_title(f"SF{sf} {q.upper()} · throughput", loc="left", fontsize=11, color=INK)
            axes[0][j].set_ylabel("queries / s", color=MUTED, fontsize=9)
            axes[1][j].set_title(f"SF{sf} {q.upper()} · main Postgres node busy cores", loc="left", fontsize=11, color=INK)
            axes[1][j].set_ylabel("cores (of 4)", color=MUTED, fontsize=9)
            axes[1][j].set_xlabel("closed-loop clients", color=MUTED, fontsize=9)
            for i in (0, 1):
                axes[i][j].set_xticks([1, 4, 8, 16])
                style(axes[i][j])
        axes[0][0].legend(frameon=False, fontsize=8)
        axes[1][0].legend(frameon=False, fontsize=8)
        fig.tight_layout()
        fig.savefig(CHARTS / f"concurrency_sf{sf}.png", dpi=150)
        plt.close(fig)


if __name__ == "__main__":
    main()
